### ISSUE TITLE
IDEA 2023.1.5报错

### ISSUE THREAD

**Issue by renfushuai** [starcwang/easy_javadoc#100]
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/88a11c59-fb51-490f-98aa-8f6858159a06)
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/21a1ea97-e87b-46ef-bfc7-250954bbd7e8)

**Comment by starcwang** [comment]
插件卸载重新安装一下试试~应该是插件初始化异常了，否则这个map不可能为空

**Comment by renfushuai** [comment]
我已经卸载重装了，不报这个错了，不过快捷键一直用不了，我以为是之前报错导致的，现在也是用不了，已经检查快捷键冲突了
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/ed55c610-7a9b-49db-97b5-de3b69ecbcd9)

**Comment by starcwang** [comment]
你是win系统吧？点一下这个 
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/7782e7b9-e194-4bf6-b187-01320bbe8426)
然后使用快捷键(ctrl+\)，看看有没有冲突

**Comment by renfushuai** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/0e701656-1386-4c86-8d63-e90a88190033)
是最后一个冲突了么，可是我去掉了重启IDEA，还是不行

**Comment by renfushuai** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/91ee8cc2-e88a-4e92-971b-3e3244b0a56e)
这是目前的快捷键配置，使用ctrl+反斜杠 没效果

**Comment by starcwang** [comment]
一闪一闪的光标是放在类名或者方法属性上按快捷键不？注意不是选中。
如果是的话，把粉色框里的改成一个独一无二的的快捷键试试。
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/c3bc287a-058c-428c-8eae-117b531ac907)

**Comment by renfushuai** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/79c25adc-2676-4191-a3cf-3ceebc846f34)
一闪一闪的光标是放在类名或者方法属性上按快捷键不？是的，不是选中

**Comment by renfushuai** [comment]
改成独一无二的也是不行，之前版本的idea是没问题的

**Comment by starcwang** [comment]
奇怪了。。。右下角也没报错？有插件求打赏的弹窗不？

**Comment by renfushuai** [comment]
有的
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/05d36c7c-d07c-4660-8f11-68774728e7a3)

**Comment by starcwang** [comment]
我测试一下这个版本

**Comment by renfushuai** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/13640261/40e08e7c-4863-4d86-97bf-80b33302c598)
我升级了一下idea ，好使了，感谢大佬耐心解答

**Comment by starcwang** [comment]
666，没想到idea小版本还挺坑
