### ISSUE TITLE
关于翻译的建议

### ISSUE THREAD

**Issue by yeyt97** [starcwang/easy_javadoc#103]
希望能自动拆分驼峰命名的字符串

**Comment by starcwang** [comment]
有case不？按理说现在已经拆分了呀

**Comment by yeyt97** [comment]
选中变量按ctrl+\翻译不行

**Comment by yeyt97** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/47516455/863e9971-638f-40c6-8897-c99eaee3b5e9)

**Comment by starcwang** [comment]
@yeyt97 知道了，下一个版本优化一下

**Comment by starcwang** [comment]
v3.4.2版本已优化
