### ISSUE TITLE
生成注释时自带换行

### ISSUE THREAD

**Issue by WiseSheep1** [starcwang/easy_javadoc#104]
新版本生成注释自带换行，有什么办法能去掉吗。

**Comment by starcwang** [comment]
@WiseSheep1 是使用了自定义格式的吗？把自定义格式最后的空行去掉，应该就可以了

**Comment by WiseSheep1** [comment]
> 

![image](https://github.com/starcwang/easy_javadoc/assets/96505419/d27f19f6-7fc3-4ac0-9fad-e4827e710264)
使用的是默认的

**Comment by starcwang** [comment]
@WiseSheep1 收到，我也复现了，我看一下

**Comment by starcwang** [comment]
@WiseSheep1 修复了一版：v3.4.3
