### ISSUE TITLE
添加注释时，导致IDEA窗口卡住好几秒

### ISSUE THREAD

**Issue by zpj80231** [starcwang/easy_javadoc#106]
几乎是必现的，考虑可能是默认翻译超时导致的？后来换成百度翻译添加API、KEY后也是这问题。我记得之前快捷键直接就出来了，没这么卡。
目前是最新版本：3.4.3。

**Comment by starcwang** [comment]
现在翻译是串行的，有可能会卡主界面几秒，我加了缓存机制来缓解此情况。
网络不好的情况也可能导致卡顿。
后边考虑开个线程池，请求接口并行化。

**Comment by zpj80231** [comment]
是的，是有缓存机制，期望后续优化一下吧🤭

**Comment by 14195111818** [comment]
真的好卡啊，之前在别的电脑没觉得，换了新电脑才感知到，3.4.3， 期望更新优化
