### ISSUE TITLE
翻译的顺序有点奇怪

### ISSUE THREAD

**Issue by eschervr-dev** [starcwang/easy_javadoc#109]
比如下面这个例子：

    /**
     * 获取根据代码
     *
     * @param deviceCode 设备代码
     * @return {@link Device}
     */
    Device getByCode(String deviceCode);

翻译出来竟然是 “获取根据编码”

如果这个getByCode放到翻译软件里，比如有道翻译，翻译出来的是“按代码获取”

**Comment by starcwang** [comment]
@eschervr-dev 看下你的自定义词典中，是否有get by code中的单词配置。如果有的话，就不会整句翻译了。
