### ISSUE TITLE
IDEA2019.3插件库搜不到了？

### ISSUE THREAD

**Issue by qinkangdeid** [starcwang/easy_javadoc#11]
如题
![image](https://user-images.githubusercontent.com/17582522/69840371-42015780-1296-11ea-8ea6-6471193f9fe3.png)

**Comment by starcwang** [comment]
我的版本控制有问题，这就修复下

**Comment by qinkangdeid** [comment]
好的列

**Comment by starcwang** [comment]
上传了，你先手动装下试试，如果不好使，还得等我周末研究研究

**Comment by qinkangdeid** [comment]
> 上传了，你先手动装下试试，如果不好使，还得等我周末研究研究

好的

**Comment by qinkangdeid** [comment]
> 上传了，你先手动装下试试，如果不好使，还得等我周末研究研究

放到插件目录了  设置界面没有出来插件

**Comment by starcwang** [comment]
好吧，我周末研究研究

**Comment by starcwang** [comment]
@qinkangdeid 已上传最新版本，可以在release中下载更新，或者等IDEA官方审核通过自动更新。

**Comment by qinkangdeid** [comment]
> @qinkangdeid 已上传最新版本，可以在release中下载更新，或者等IDEA官方审核通过自动更新。

nice 感谢
