### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LiJunYi2** [starcwang/easy_javadoc#113]
**IDEA** ：2023.2.1
**插件版本**：3.4.3
使用的是**阿里云翻译**

**异常信息如下：**

请求阿里云翻译接口异常：请检查本地网络是否可连接外网，也有可能被阿里云限流
  
  java.lang.NullPointerException: Cannot invoke "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseDataVO.getTranslated()" because the return value of "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseVO.getData()" is null

**Comment by starcwang** [comment]
本地调用一下，看阿里云接口是通的吗

**Comment by eschervr-dev** [comment]
我也用的阿里云翻译，也是一样的错

**Comment by wl-bit** [comment]
确实 我也碰到了  ，本地用accessKeyId和secret验证过 没有问题

**Comment by starcwang** [comment]
@wl-bit @LiJunYi2 @eschervr-dev 收到，那应该是程序的问题了，我抓紧修一下。

**Comment by starcwang** [comment]
v3.5.0版本已修复
