### ISSUE TITLE
模板报错

### ISSUE THREAD

**Issue by ciweigg2** [starcwang/easy_javadoc#12]
/**
* $DOC$
*/

为什么这样配置还报错

![image](https://user-images.githubusercontent.com/41536971/70587026-cbece100-1c03-11ea-9614-1557588efc0b.png)

能给个不报错的正确例子么

**Comment by starcwang** [comment]
哎呀，有bug

**Comment by starcwang** [comment]
![image](https://user-images.githubusercontent.com/18590960/70587287-87157a00-1c04-11ea-80e5-c8b1c2d1c8b7.png)
我这刚才少写了个!

**Comment by ciweigg2** [comment]
图裂了- -那就是bug咯 等你新版

**Comment by ciweigg2** [comment]
groovy脚本的例子有么 我之前用我以前的脚本 不行

**Comment by starcwang** [comment]
new GroovyShell(new Binding(变量)).evaluate(脚本).toString();

**Comment by starcwang** [comment]
idea插件已提交审核。

**Comment by ciweigg2** [comment]
new GroovyShell(new Binding(变量)).evaluate(脚本).toString();
这个你给我例子吧 我玩不来- - 谢谢哈
        new GroovyShell(new Binding(new String[]{"$param$"}).evaluate("groovyScript(\"if(\\\"${_1}\\\".length() == 2) {return '';} else {def result=''; def params=\\\"${_1}\\\".replaceAll('[\\\\\\\\[|\\\\\\\\]|\\\\\\\\s]', '').split(',').toList();for(i = 0; i < params.size(); i++) {if(i==0){result+='* @param ' + params[i] +' '}else{result+='\\\\n' + ' * @param ' + params[i] + ' '}}; return result;}\", methodParameters());").toString());

**Comment by starcwang** [comment]
你的这个脚本里面好多变量都没有啊，不支持这样。
我看逻辑是想去param，可以在模板里这么写：
```
/**
 * $DOC$
 * $PARAMS$
 */
```
