### ISSUE TITLE
新增java文件或者包级别一键添加注释

### ISSUE THREAD

**Issue by yoozoom** [starcwang/easy_javadoc#122]
能否新增功能，

在 java 类文件级别，或者包级别批量给类，属性，和方法添加注释。

比如：右键选择某个 java 类 -> 一键生成注释

**Comment by starcwang** [comment]
已经有这个功能，光标放在类上，使用cmd(ctrl)+shift+\ ，或者ctrl+n(mac) ctrl+Ins(win) -> 生成文档注释
