### ISSUE TITLE
翻译方式选择关闭时，能否字段已有注释可以在无法翻译时不将原来的注释去除？

### ISSUE THREAD

**Issue by HayBranch** [starcwang/easy_javadoc#125]
翻译方式选择关闭时，能否字段已有注释可以在无法翻译时不将原来的注释去除？
尤其是翻译类全部字段的时候，有时多加了几个字段，然后批量生成注释，导致之前的注释无法翻译的的注释置空了

**Comment by starcwang** [comment]
使用自定义模板了吗？
