### ISSUE TITLE
版本兼容请求

### ISSUE THREAD

**Issue by jonny6015** [starcwang/easy_javadoc#13]
公司只能使用2018的版本的IDEA 希望做下兼容
目前安装不了。使用的是2018.3.6版本

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by starcwang** [comment]
2018 和 2019版本 API差别很大，我研究研究，看能否向下兼容

**Comment by jonny6015** [comment]
先赞一个👍

**Comment by starcwang** [comment]
已支持 2018.1+ 版本
