### ISSUE TITLE
中文字段翻译成英文，为什么首字母是大写的

### ISSUE THREAD

**Issue by StackTc** [starcwang/easy_javadoc#130]
<img width="667" alt="image" src="https://github.com/starcwang/easy_javadoc/assets/22773866/47234a98-1049-4402-9aef-561143be2660">
<img width="955" alt="image" src="https://github.com/starcwang/easy_javadoc/assets/22773866/523783ab-7274-41fd-b57a-f5d5a333def2">

**Comment by starcwang** [comment]
收到，后边我优化下

**Comment by starcwang** [comment]
v3.7.0 已优化 @StackTc
