### ISSUE TITLE
重新生成注释的功能需要优化

### ISSUE THREAD

**Issue by GhyToSky** [starcwang/easy_javadoc#133]
**场景：目标对象的注释已存在，重新给该对象生成注释
当前：插件会用新注释覆盖老注释
期望：因为老注释可能是手动修改过的，不希望被破坏，所以无论是单个还是批量，都直接保留老注释，不重新生成注释**

大佬，麻烦你了 @starcwang

**Comment by starcwang** [comment]
收到，后期会优化

**Comment by GhyToSky** [comment]
大佬，年前能更新一下吗 @starcwang

**Comment by starcwang** [comment]
大佬，我尽量。。😵

**Comment by GhyToSky** [comment]
感谢

**Comment by starcwang** [comment]
@GhyToSky 大佬，更新了，v3.7.0

**Comment by GhyToSky** [comment]
![image](https://github.com/starcwang/easy_javadoc/assets/148807504/bb57c409-f1fd-46ae-a94d-671c893f5554)
插件市场没看到新版本啊 @starcwang

**Comment by starcwang** [comment]
@GhyToSky 官方还在审核，稍等两天

**Comment by GhyToSky** [comment]
好的，辛苦了 @starcwang

**Comment by starcwang** [comment]
@GhyToSky 大佬加下群，详细对对

**Comment by GhyToSky** [comment]
你看结果 @starcwang

**Comment by starcwang** [comment]
@GhyToSky 图片打不开。。。
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/2bc882fc-b7cf-42cb-bdaa-9f5a758b8793)

**Comment by GhyToSky** [comment]
重发图片了，能看到了吗 @starcwang

**Comment by starcwang** [comment]
@GhyToSky 能看到了，我知道了，我再优化下

**Comment by starcwang** [comment]
@GhyToSky 使用自定义模板吧？发我一下自定义模板内容吧

**Comment by GhyToSky** [comment]
是自定义模板，这个是我的方法模板 @starcwang 
/**
 * $METHOD_NAME$
 *
 * @author $AUTHOR$
 * @since $DATE$
 */

**Comment by GhyToSky** [comment]
模板发你了，应该可以搞定吧 @starcwang

**Comment by starcwang** [comment]
模板收到了，我有时间搞一下

**Comment by GhyToSky** [comment]
大佬，没忘吧 @starcwang

**Comment by starcwang** [comment]
@GhyToSky v3.7.1 提交审核了

**Comment by GhyToSky** [comment]
好的，我试试 @starcwang

**Comment by GhyToSky** [comment]
大佬，没有完全正确啊，你现在是部分内容不重新生成，部分内容却又重新生成，不是说好的全都不重新生成嘛 @starcwang 
![image](https://github.com/starcwang/easy_javadoc/assets/148807504/19a59130-a7db-4458-97a5-4cc6acc730ca)

**Comment by GhyToSky** [comment]
大佬，没有完全正确啊，你现在是部分内容不重新生成，部分内容却又重新生成，不是说好的全都不重新生成嘛 @starcwang 
![image](https://github.com/starcwang/easy_javadoc/assets/148807504/19a59130-a7db-4458-97a5-4cc6acc730ca)

**Comment by GhyToSky** [comment]
大佬，麻烦再改下吧，辛苦了 @starcwang

**Comment by starcwang** [comment]
好的，这两周有点忙，我加个配置来配置它是merge还是忽略吧

**Comment by starcwang** [comment]
v3.8.0加了个开关，你的这个情况选忽略就好了
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/5d336d2a-c68d-4422-b727-c663d07e1339)

**Comment by GhyToSky** [comment]
可以了，感谢大佬 @starcwang
