### ISSUE TITLE
command + \ 快捷键失效问题

### ISSUE THREAD

**Issue by peanut0713** [starcwang/easy_javadoc#135]
老板，
IntelliJ IDEA 2023.3 的版本开始，command + \ 默认是idea的 AI Assistant的启动的快捷键组合，easy_doc可以支持更换触发的快捷键组合吗，我找了一会貌似没找到

**Comment by starcwang** [comment]
有
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/215d81cb-d759-407f-8279-fe84a22e09bd)
