### ISSUE TITLE
重新生成参数 @params 前面的 * 号没有了

### ISSUE THREAD

**Issue by unclezs** [starcwang/easy_javadoc#138]
如下图：
![shot](https://github.com/starcwang/easy_javadoc/assets/42318775/a9ded445-5a27-4811-8df3-3cf95d79a3b9)

idea 版本号：
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023

**Comment by starcwang** [comment]
看看是不是idea的javadoc格式化关了？
![image](https://github.com/starcwang/easy_javadoc/assets/18590960/690694ef-c121-4f77-8f48-87ab266d767a)

**Comment by unclezs** [comment]
确实是，我记得没有操作过，升级上来突然就这样了，感谢感谢~
