### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3.3)

### ISSUE THREAD

**Issue by skipper-sj** [starcwang/easy_javadoc#145]
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3.3)

**Comment by starcwang** [comment]
截图一下我看看都有哪些插件？我升级了2023.3.3版本，无问题

**Comment by skipper-sj** [comment]
按照你说的，我排查了下，是ai assistant的快捷键冲突了，感谢
