### ISSUE TITLE
可以实现右键项目，然后一键生成自定义模板注释的内容，这种功能吗

### ISSUE THREAD

**Issue by hanhaoq** [starcwang/easy_javadoc#146]
义父，义父，义父。能抽个空实现一下这个功能吗，或者讲一下大致思路，让小的自己琢磨琢磨

**Comment by starcwang** [comment]
由于修改文件是同步操作，所以这样会导致ide卡很久很久甚至无响应。。体验很差。所以不打算支持此功能
