### ISSUE TITLE
类注释默认生成的有问题

### ISSUE THREAD

**Issue by cheyiming** [starcwang/easy_javadoc#153]
生成的标签@description后面的冒号跟date和auth后面的冒号不一样，且@description冒号前面少了一个空格，造成idea每次都会认为是wrong tag，必须改成自定义模板才行，例如这样：
/**
 * @author ： $AUTHOR$
 * @date ： Created in $DATE$	
 * @description ： $DOC$
 */

**Comment by starcwang** [comment]
没明白，你这看起来不挺正常的么？自定义模板不生效吗？

**Comment by cheyiming** [comment]
> 没明白，你这看起来不挺正常的么？自定义模板不生效吗？

我刚刚在插件中选择“重置”+“清空缓存”后，发现类的注释并没有默认生成@description标签，不清楚为什么以前会默认生成一个@description标签。发两张截图吧
![有问题](https://github.com/starcwang/easy_javadoc/assets/12655044/8029c24d-4f10-4a41-8bb3-2f97fe0b9614)
![自定义正常](https://github.com/starcwang/easy_javadoc/assets/12655044/1b3724b2-a77a-4364-8c5d-c45d17188a3d)

**Comment by cheyiming** [comment]
找到问题了，是我idea设置的创建类时默认生成的注释格式不对，位置在Editor>File and COde Templates>Includes，抱歉
