### ISSUE TITLE
使用谷歌翻译为什么一定要GoogleKey？

### ISSUE THREAD

**Issue by lihaojiee** [starcwang/easy_javadoc#156]
本地挂梯子或者配置host都可以流畅使用谷歌翻译，例如Translation插件选择谷歌翻译并不需要添加其他配置。

**Comment by starcwang** [comment]
@lihaojiee 已经添加了google免费翻译了

**Comment by lihaojiee** [comment]
@starcwang 请问v4.1.0上架IDEA插件市场了吗？
