### ISSUE TITLE
突然生成的注释里没有中文翻译了，其他的还在，什么原因呢？

### ISSUE THREAD

**Issue by iyinghui** [starcwang/easy_javadoc#157]
使用了有道云的api 的 appkey 和 秘钥，开始是好好的，本月15号突然不能用了，有注册了阿里云api 的appkey， 试了还是不行。
<img width="966" alt="image" src="https://github.com/starcwang/easy_javadoc/assets/16011499/7d29ff4a-05cd-4f4c-912d-ec719a792ab1">
点击快捷键的效果如下
```
/**
 * @author admin
 * @date 2024/05/16
 */
```

15号发生的唯一特别的事情，就是idea专业版以前的激活失效了，今天重新激活了一下。不知道和它有没有关系。
我用的idea是2024.1    mac 版本的 
easyUI用的是 4.0.0

**Comment by laihaibing** [comment]
我也遇到了相同的问题，翻译换成其他平台的，不会自动生成中文注释

**Comment by starcwang** [comment]
私聊下我看看问题

**Comment by 779943132** [comment]
我原来也出现这个问题了，现在已经解决了，你看一下你的idea是不是配置了代理，我的就是因为idea配置了代理导致的，把代理取消了就可以了
