### ISSUE TITLE
feature:在调用三方时，希望使用异步方式，或提供同步超时时间设置

### ISSUE THREAD

**Issue by LinkeyZ** [starcwang/easy_javadoc#159]
在使用中，由于种种原因，翻译无法在 1s 中返回，整个 idea 卡死，影响使用。希望提供异步版本或同步超时设置

**Comment by starcwang** [comment]
@LinkeyZ 请求生成代码必须是阻塞的。超时时间有的，现在是1s

**Comment by starcwang** [comment]
@LinkeyZ v4.1.0版本支持设置超时时间了
