### ISSUE TITLE
公司内网希望有一个本地词库可以指向翻译

### ISSUE THREAD

**Issue by zqh12348** [starcwang/easy_javadoc#163]
公司内网不能使用第三方翻译软件，希望能有一个本地的来作为翻译的词库

**Comment by starcwang** [comment]
可以先导出配置，然后修改配置文件，再导入

**Comment by starcwang** [comment]
![image](https://github.com/user-attachments/assets/e5df51e3-2c2d-4c31-908e-60c0293820ee)
@zqh12348 新版支持了本地词典（可能翻译不准）和自定义http接口。
