### ISSUE TITLE
插件本身的快捷键可以修改吗？我没找到能修改的地方呢？

### ISSUE THREAD

**Issue by thiscuiyao** [starcwang/easy_javadoc#168]
我是Mac电脑，command+/这个组合是单行注释快捷键，我使用频率比较高。
所以想看看能不能修改插件本身的快捷键。

**Comment by starcwang** [comment]
默认的快捷键是command+\ （往右下角倾斜，和你给的不一样）。
想改也可以，在设置里，快捷键那，搜下 `javadoc` ，可以修改

**Comment by thiscuiyao** [comment]
1.我马虎了，“command+\”确实可以，是我看错了。
2.修改快捷键的地方也找到了

感谢回答，麻烦了
