### ISSUE TITLE
Javadoc渲染问题

### ISSUE THREAD

**Issue by AD1026** [starcwang/easy_javadoc#169]
请教一下，自定义的javadoc标签会触发警告，并且在渲染模式下不显示，应该怎么去设置呢？
<img width="997" alt="图片" src="https://github.com/user-attachments/assets/76fe37b9-de6c-4c56-8502-6d37f9bef6f8">
<img width="954" alt="图片" src="https://github.com/user-attachments/assets/aa7bc062-33ae-49f5-8e48-b4def33d6b90">

推荐的处理也只会消除警告，但是在渲染模式下依然不显示自定义的标签。
<img width="707" alt="图片" src="https://github.com/user-attachments/assets/19bd2195-a7de-47b0-92e9-e3d087e2ea0a">

**Comment by starcwang** [comment]
这个是idea的策略，我没办法搞。。
