### ISSUE TITLE
最近有时候可以翻译 有时候不行

### ISSUE THREAD

**Issue by qinkangdeid** [starcwang/easy_javadoc#20]
最近有时候可以翻译 有时候不行 只生成一个注释符合
![image](https://user-images.githubusercontent.com/17582522/76090706-fc6fcb80-5ff6-11ea-8735-9d7a58ecac4a.png)

**Comment by starcwang** [comment]
还没遇到过这个情况，翻译强依赖网络，是不是网络情况太差导致的？
