### ISSUE TITLE
已有doc时提供覆盖选项

### ISSUE THREAD

**Issue by mzzsfy** [starcwang/easy_javadoc#21]
当已经写了一部分doc时,考虑提供不覆盖的选项?
或者提供弹框让用户选择保留哪一块

**Comment by starcwang** [comment]
在默认模式下（非自定义），当前已经实现了**方法**和**类**注释的已有不覆盖功能。

**Comment by mzzsfy** [comment]
如何使用?idea版本为2020.1,插件版本为1.11,没有办法不覆盖原doc

**Comment by starcwang** [comment]
doc标签会有部分覆盖，注释会有追加

**Comment by mzzsfy** [comment]
覆盖和保留的情况都有,插件挺好用,还是希望可以提供更多的选择空间
