### ISSUE TITLE
属性注释不能单独一行

### ISSUE THREAD

**Issue by BenAmoC** [starcwang/easy_javadoc#23]
老板，我的IDEA是2019.3.3， 给属性设置注释的时候不能单独成行

**Comment by starcwang** [comment]
默认IDE的代码格式化会将一行变成多行，在这设置下就行了

![image](https://user-images.githubusercontent.com/18590960/86482899-6f126d00-bd85-11ea-9cf6-75fd9395f1aa.png)

**Comment by BenAmoC** [comment]
搞定，多谢
