### ISSUE TITLE
自定义模板不能单独设置

### ISSUE THREAD

**Issue by z2z2qp** [starcwang/easy_javadoc#24]
类注释模板配置、方法注释模板配置，属性注释模板配置，不能单独生效，一旦某一个设置了自定义，其他两条就会跟随这一个设置

**Comment by starcwang** [comment]
我这没有复现，提供下IDEA版本和导出的配置文件吧

**Comment by mcp2016** [comment]
一样的问题，idea 2019.1.3。类模板、方法模板、属性模板设置任意一个，并应用，都会覆盖其他两个

**Comment by starcwang** [comment]
> 一样的问题，idea 2019.1.3。类模板、方法模板、属性模板设置任意一个，并应用，都会覆盖其他两个

有导出的配置文件吗？我看看

**Comment by summitxf** [comment]
这个问题我这边也有

**Comment by starcwang** [comment]
@summitxf  @z2z2qp  @mcp2016  已修复，请尝试1.14版本
