### ISSUE TITLE
翻译只有有道，不能进行切换

### ISSUE THREAD

**Issue by tianyangw** [starcwang/easy_javadoc#25]
工具特别好用，但是有道的接口调用多了就会出验证码，不让用了，想切换翻译器，我看其他翻译器的代码有，但是idea的配置下拉没有，跪求修改一波，3QQQQQQ
![image](https://user-images.githubusercontent.com/29446939/90238885-3d4af680-de59-11ea-8bea-fb8a03e3ebc8.png)
![image](https://user-images.githubusercontent.com/29446939/90238967-65d2f080-de59-11ea-8e3a-9a7d16c2de23.png)

**Comment by starcwang** [comment]
其他的翻译都有限流，使用起来效果并不好，更好的翻译api还在调研中

**Comment by tianyangw** [comment]
收到了你的更新，期间我自己也查了下，百度api的高级版本每个月有200万字符是免费的，调用量每秒10次。
并且接口调用时一次可以传入多个单词。我自己改了改用起来体验还不错，由于公司安全政策代码没法上传，我把我的想法同步给你。
1、合并一个方法、类、变量名的翻译请求为一次，降低调用频次
2、增加一层中间服务做缓存，翻译请求通过http缓存服务，先取缓存信息，如果没有再去翻译网站
3、把baidu的api key做成可配置的，让使用者自行修改
我是做了前两个，工具已经可以供小规模人同时使用了，如果做了第三个这样使用人员可以自行申请key，及时没有缓存也能有很好的体验了

**Comment by starcwang** [comment]
感谢，3已经着手开始做了，用户自己填写key，打算支持百度翻译和腾讯翻译两家。

**Comment by starcwang** [comment]
已支持自定义翻译平台
