### ISSUE TITLE
将光标放置到想要生成注释的类、方法或者属性上，然后按下快捷键ctrl \只会翻译类，并不会自动生成类注释

### ISSUE THREAD

**Issue by qian-zq** [starcwang/easy_javadoc#26]
![image](https://user-images.githubusercontent.com/49049935/94221743-4df19080-ff1e-11ea-89a4-dbfc77bcf558.png)

**Comment by starcwang** [comment]
不要双击选择方法，光标放到上面单击，按快捷键即可
双击选择后会变成翻译功能
