### ISSUE TITLE
如何获取类名

### ISSUE THREAD

**Issue by summitxf** [starcwang/easy_javadoc#27]
自定义模板
```
/**
 * <p>
 * <b>Class name</b>: $name$ $className$ $simpleClassName$
 * </p>
 * <p>
 * <b>Class description</b>: $DOC$
 * </p>
 * <p>
 * <b>Author</b>: $AUTHOR$
 * </p>
 */
```
$className$ $simpleClassName$ 都获取不到

然后用自定义变量，使用groovy还是不行

```
new GroovyShell(new Binding("$name$")).evaluate("groovyScript("def result=${_1}; return result", className())").toString();
```

**Comment by starcwang** [comment]
![image](https://user-images.githubusercontent.com/18590960/101992183-43d36880-3ca9-11eb-91e9-71ecb4dafb31.png)

类型 ：groovy脚本
自定义值：className

**Comment by zhengdahanlei** [comment]
想问下怎么获取类名和方法名,
![image](https://user-images.githubusercontent.com/31740643/102773850-df10c000-43c4-11eb-9df1-b62f5b3861c6.png)

![image](https://user-images.githubusercontent.com/31740643/102773824-d3bd9480-43c4-11eb-9165-9b3d481b5610.png)

我按照如上设置,并没有出现类名
