### ISSUE TITLE
自定义方法注释模板注解问题

### ISSUE THREAD

**Issue by bennick1** [starcwang/easy_javadoc#28]
使用自定义模板时发现如下问题：
1.生成顺序
/** 
 * @methodName $methodName$
 * 
 * $PARAMS$
 * @return $RETURN$
 * $THROWS$
 */
这是我定义的模板，但是生成的注释变成了
/**
 * @param test
 * @methodName test
 */
2.如果不加@return，只有$RETURN$，生成的注释会将返回类型放在param参数说明后面

**Comment by starcwang** [comment]
注释的顺序是在IDEA里 editor -> code style -> java -> javadoc 里设置的，格式化代码的时候自动给排序了
