### ISSUE TITLE
返回值类型含有泛型时，文档注释不准确

### ISSUE THREAD

**Issue by MHLiu1219** [starcwang/easy_javadoc#39]
![image](https://user-images.githubusercontent.com/34827641/121488741-f3de2000-ca05-11eb-9325-b0b0121e1de4.png)
原因应该时注释里面含有  <  和   >，因为文档注释是支持html标签， < 会导致冲突
如果可以的话，希望可以生成下面这种注释
![image](https://user-images.githubusercontent.com/34827641/121489594-cf367800-ca06-11eb-8a00-f1e6e72d8d11.png)

**Comment by Taogang00** [comment]
@return {@link R<PageResult<SysUserDTO>> }  
Illegal character 

 遇到同样的嵌套泛型的问题，希望可以改进，谢谢~~

**Comment by sy714573037** [comment]
自己下代码改改吧，MethodDocGenerator这个方法里。

**Comment by starcwang** [comment]
v1.21版本优化了此功能
