### ISSUE TITLE
局部变量 不好加吧，看了代码 PsiLocalVariable没法在上面加

### ISSUE THREAD

**Issue by CaiGaoQing** [starcwang/easy_javadoc#4]

**Comment by CaiGaoQing** [comment]
![image](https://user-images.githubusercontent.com/29398395/68822603-50fbdd80-06cc-11ea-875b-abb40a59bcf3.png)

**Comment by starcwang** [comment]
@CaiGaoQing  局部变量不属于文档注释范畴，今后视情况低优先级支持~
