### ISSUE TITLE
IDEA 2021.1.2报错

### ISSUE THREAD

**Issue by AncientFairy** [starcwang/easy_javadoc#42]
Attempt to modify PSI for non-committed Document!

![IDEA插件报错](https://user-images.githubusercontent.com/25677587/122402534-282a8100-cfb0-11eb-88f5-7aa25f08c013.png)

**Comment by starcwang** [comment]
怀疑是使用方式不对，，我这复现不了这个问题

**Comment by AncientFairy** [comment]
哈哈





------------------ 原始邮件 ------------------
发件人: 王超 ***@***.***&gt;
发送时间: 2021年7月3日 16:43
收件人: starcwang/easy_javadoc ***@***.***&gt;
抄送: 许大仙 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[starcwang/easy_javadoc] IDEA 2021.1.2报错 (#42)





 
怀疑是使用方式不对，，我这复现不了这个问题
