### ISSUE TITLE
@see标签不支持在方法上使用，是否可以考虑支持一下呢？

### ISSUE THREAD

**Issue by lan149** [starcwang/easy_javadoc#49]
试用了一下作者的插件，做的很棒啊！比IDEA原来的注释方式都好用！但是美中不足的是，@see标签不支持在方法上使用，是否可以考虑支持一下呢？有一些方法上还是很必要用@see标签的。

**Comment by starcwang** [comment]
可以试试v1.27版本的自定义模板功能
