### ISSUE TITLE
希望字段上的注释不覆盖原有 tag 信息

### ISSUE THREAD

**Issue by gudqs7** [starcwang/easy_javadoc#54]
如:
```java

    /**
     * 用户id
     * #required
     * @example 1
     */
    private Long userId;
```

中的 `#required` 和 `@example` 两行信息

**Comment by starcwang** [comment]
目前是会保留的，可能是ide配置有问题，请检查下如下配置
![image](https://user-images.githubusercontent.com/18590960/189491906-ceccfa05-2920-4438-8d03-e4b10b535a4c.png)
