### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by n7tequila** [starcwang/easy_javadoc#56]
如果在一个已经生成过一次注释的方法上重新再生成一次，方法说明、参数的说明是不会被替换的，但是返回值和抛出错误的注释部分，就算是已经有了，也会被覆盖的。
还有就是，如果是构造方法，能不能自动不生成@return的项目呀

**Comment by starcwang** [comment]
你应该是用的自定义模板吧？自定义模板属于强制行为，都会覆盖原结果哈
