### ISSUE TITLE
生成link模式的返回值时报错

### ISSUE THREAD

**Issue by cheakin** [starcwang/easy_javadoc#59]
生成link模式的返回值时，取到的返回类型并不是完整的， 如图：
![image](https://user-images.githubusercontent.com/29295460/176344774-4cfb0d6b-6a51-4f76-a694-b02516cf882c.png)
其中Resp是MhFpFdFunddownPlanGrantSelectPageListVO的内部静态类

**Comment by starcwang** [comment]
感谢，已修复，v1.27
