### ISSUE TITLE
建议自定义配置有道的appkey appId

### ISSUE THREAD

**Issue by xiamaoxuan** [starcwang/easy_javadoc#6]
建议自定义配置有道的appkey appId，翻译更准确，还有翻译方法名的时候建议切词成句，把句子直接翻译，翻译的准确性会高很多

**Comment by starcwang** [comment]
好建议，后续考虑支持~

**Comment by starcwang** [comment]
已经支持整句翻译

**Comment by xiamaoxuan** [comment]
整句翻译怎么用呢？还是说方法名和类名这种默认就是使用的整句翻译？

**Comment by xiamaoxuan** [comment]
比如说getAreaByAreaId(String areaId) {}这种方法，翻译出来的结果就会很奇怪，如果支持方法整句翻译的话，就很爽

**Comment by starcwang** [comment]
现在的逻辑是如果所有单词中没有命中自定义的单词，就会走整句翻译
