### ISSUE TITLE
1.27版本，自定义翻译失效

### ISSUE THREAD

**Issue by supermingjun** [starcwang/easy_javadoc#68]
插件版本：1.27
IDEA版本：2022.2.3(222.4345.14)
<img width="434" alt="image" src="https://user-images.githubusercontent.com/39512777/195877177-c087211f-6226-4683-a8d6-c3e82c34e68f.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/39512777/195978322-11a4f5b1-39d4-4796-8a81-959b579b9b60.png">

**Comment by starcwang** [comment]
@supermingjun 大小写问题，v1.28版本已修复

**Comment by EGo14T** [comment]
![image](https://user-images.githubusercontent.com/28916447/198540459-21de472c-17a2-462a-8426-0da49b75215d.png)
![image](https://user-images.githubusercontent.com/28916447/198540972-be53d20c-6530-4156-a200-91bb3eadc6c7.png)


还是有问题 版本 1.28
