### ISSUE TITLE
请问自己配置的翻译设置文件是存在哪里的？

### ISSUE THREAD

**Issue by qinkangdeid** [starcwang/easy_javadoc#7]
请问自定义单词映射的位置是在哪里 我有多台设备 想要同步一下这个设置
![image](https://user-images.githubusercontent.com/17582522/68912885-6fc5a700-0794-11ea-9d84-91f2cfcd4a91.png)

**Comment by starcwang** [comment]
@qinkangdeid  mac本路径在：/Users/你的名字/Library/Preferences/IntelliJIdea2019.2/options/easyJavadoc.xml 文件中
win本应该也在用户路径里，可以通过文件名`easyJavadoc.xml`找找。
