### ISSUE TITLE
找不到Easy Kdoc

### ISSUE THREAD

**Issue by Klosw** [starcwang/easy_javadoc#76]
在插件中找不到 Easy Kdoc

**Comment by whosmyqueen** [comment]
+1

**Comment by Klosw** [comment]
> @Klosw @whosmyqueen 各位老铁不好意思。。我临时下线了。 因为Easy Javadoc和Easy Kdoc快捷键有冲突，导致IDE启动报错，二者只能有一个存在，我先解决下这个妖。

原来如此 大佬加油

**Comment by Mr-FB** [comment]
加油

**Comment by starcwang** [comment]
@Klosw @whosmyqueen @Mr-FB 各位更新下Easy Javadoc 3.0.0版本吧~两个插件合二为一了

**Comment by Mr-FB** [comment]
亲你的邮件我已经收到了。
