### ISSUE TITLE
自动生成方法注释结束后无换行

### ISSUE THREAD

**Issue by lixunhui** [starcwang/easy_javadoc#77]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/4917509/207268762-a5dcc15f-01f0-462c-9396-2bd6b7e74ed2.png">
如上图代码Demo代码中所示,应该在注释结束后换行,正确格式如下:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/4917509/207269199-a9f847e1-dc9f-401f-acc1-11198d3c64ab.png">

**Comment by kuolemax** [comment]
> <img alt="image" width="753" src="https://user-images.githubusercontent.com/4917509/207268762-a5dcc15f-01f0-462c-9396-2bd6b7e74ed2.png">
> 
> 如上图代码Demo代码中所示,应该在注释结束后换行,正确格式如下:
> <img alt="image" width="757" src="https://user-images.githubusercontent.com/4917509/207269199-a9f847e1-dc9f-401f-acc1-11198d3c64ab.png">

1. 你使用的插件版本是多少?
2. 你的idea版本是多少?

我这里使用idea-u 2022.3 , 插件版本3.0.0是正常的

**Comment by kuolemax** [comment]
> > > <img alt="image" width="753" src="https://user-images.githubusercontent.com/4917509/207268762-a5dcc15f-01f0-462c-9396-2bd6b7e74ed2.png">
> > > 如上图代码Demo代码中所示,应该在注释结束后换行,正确格式如下:
> > > <img alt="image" width="757" src="https://user-images.githubusercontent.com/4917509/207269199-a9f847e1-dc9f-401f-acc1-11198d3c64ab.png">
> > 
> > 
> > 
> > 1. 你使用的插件版本是多少?
> > 2. 你的idea版本是多少?
> > 
> > 我这里使用idea-u 2022.3 , 插件版本3.0.0是正常的
> 
> 我的版本号和您的版本号是一样的,难道是我的IDEA代码样式的问题? <img alt="image" width="609" src="https://user-images.githubusercontent.com/4917509/207278289-15a0b87c-a064-4936-8e4a-22226e19ea3f.png">

我的设置是这样的
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/25677528/207279556-b68240a2-6d69-4556-b622-52f40efe746d.png">

**Comment by lixunhui** [comment]
> > > > <img alt="image" width="753" src="https://user-images.githubusercontent.com/4917509/207268762-a5dcc15f-01f0-462c-9396-2bd6b7e74ed2.png">
> > > > 如上图代码Demo代码中所示,应该在注释结束后换行,正确格式如下:
> > > > <img alt="image" width="757" src="https://user-images.githubusercontent.com/4917509/207269199-a9f847e1-dc9f-401f-acc1-11198d3c64ab.png">
> > > 
> > > 
> > > 
> > > 1. 你使用的插件版本是多少?
> > > 2. 你的idea版本是多少?
> > > 
> > > 我这里使用idea-u 2022.3 , 插件版本3.0.0是正常的
> > 
> > 
> > 我的版本号和您的版本号是一样的,难道是我的IDEA代码样式的问题? <img alt="image" width="609" src="https://user-images.githubusercontent.com/4917509/207278289-15a0b87c-a064-4936-8e4a-22226e19ea3f.png">
> 
> 我的设置是这样的 <img alt="image" width="1231" src="https://user-images.githubusercontent.com/25677528/207279556-b68240a2-6d69-4556-b622-52f40efe746d.png">

我改成和您一样的设置,还是存在同样的问题

**Comment by kuolemax** [comment]
> > > > > <img alt="image" width="753" src="https://user-images.githubusercontent.com/4917509/207268762-a5dcc15f-01f0-462c-9396-2bd6b7e74ed2.png">
> > > > > 如上图代码Demo代码中所示,应该在注释结束后换行,正确格式如下:
> > > > > <img alt="image" width="757" src="https://user-images.githubusercontent.com/4917509/207269199-a9f847e1-dc9f-401f-acc1-11198d3c64ab.png">
> > > > 
> > > > 
> > > > 
> > > > 1. 你使用的插件版本是多少?
> > > > 2. 你的idea版本是多少?
> > > > 
> > > > 我这里使用idea-u 2022.3 , 插件版本3.0.0是正常的
> > > 
> > > 
> > > 我的版本号和您的版本号是一样的,难道是我的IDEA代码样式的问题? <img alt="image" width="609" src="https://user-images.githubusercontent.com/4917509/207278289-15a0b87c-a064-4936-8e4a-22226e19ea3f.png">
> > 
> > 
> > 我的设置是这样的 <img alt="image" width="1231" src="https://user-images.githubusercontent.com/25677528/207279556-b68240a2-6d69-4556-b622-52f40efe746d.png">
> 
> 我改成和您一样的设置,还是存在同样的问题

我现在用的是mac版的, 晚上我用win版试试, 您可以试试卸载插件后重新安装, 也许可以解决这个问题. 或者看下是否使用了自定义模板.

**Comment by lixunhui** [comment]
我也是MAC版本,我检查一下Code Template看看

**Comment by kuolemax** [comment]
我在win上也试过了，默认设置下生成的doc没有出现该问题。建议您卸载重装下本插件试试。
