### ISSUE TITLE
版本号是否可以做成动态获取或者解析git分支版本号

### ISSUE THREAD

**Issue by NobiLee** [starcwang/easy_javadoc#81]
目前设置项目版本号只能使用固定值，每次版本变更时都需要更新版本号，并且可能同时存在多个版本一起开发的情况。另外是否可以提供一个groovy脚本的示例？

**Comment by starcwang** [comment]
如果引入git分支作为变量能满足需求不？
或者你看看还需要别的变量不？

**Comment by starcwang** [comment]
v3.3.1版本已添加git分支作为变量
![image](https://user-images.githubusercontent.com/18590960/236983117-6af2446c-4d01-4fce-9edf-79399ba21540.png)
