### ISSUE TITLE
我的m1pro 最新版本idea点击使用快捷键翻译的时候会卡死

### ISSUE THREAD

**Issue by 0xd3d** [starcwang/easy_javadoc#83]
我的m1pro 最新版本idea点击使用快捷键翻译的时候会卡死,但是我本身idea的插件是可以正常翻译的

**Comment by yangcanlin** [comment]
是的，当你采用有道翻译时会卡顿一下，好像是最近才发生的，可以临时切换到阿里云翻译使用，每月免费100万额度足够翻译方法名称了，切记小心使用，因为超额可能会导致欠费。

**Comment by yangcanlin** [comment]
> 是的，当你采用有道翻译时会卡顿一下，好像是最近才发生的，可以临时切换到阿里云翻译使用，每月免费100万额度足够翻译方法名称了，切记小心使用，因为超额可能会导致欠费。

好吧,好像阿里云也会出现这个问题,刚刚我为什么没有出现可能是因为缓存,现在出现了.

**Comment by 0xd3d** [comment]
卡顿应该是调取翻译接口的时候出现的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [starcwang/easy_javadoc] 我的m1pro 最新版本idea点击使用快捷键翻译的时候会卡死 (Issue #83)





  
是的，当你采用有道翻译时会卡顿一下，好像是最近才发生的，可以临时切换到阿里云翻译使用，每月免费100万额度足够翻译方法名称了，切记小心使用，因为超额可能会导致欠费。
  
好吧,好像阿里云也会出现这个问题,刚刚我为什么没有出现可能是因为缓存,现在出现了.

**Comment by starcwang** [comment]
@yangcanlin 感谢帮助！
@0xd3d 目前翻译走网络请求，是同步的，如果批量翻译、网不好、或者接口响应慢，是可能导致卡顿的。

**Comment by yangcanlin** [comment]
> @yangcanlin 感谢帮助！ @0xd3d 目前翻译走网络请求，是同步的，如果批量翻译、网不好、或者接口响应慢，是可能导致卡顿的。

好的，请求加入谷歌翻译，类似 Translation 插件，我一直在使用他的谷歌接口翻译。主要是它的翻译对于程序员开发比较准确，比如输入 img  image  谷歌翻译都是 图像/图片，但别的翻译可能翻译不出来 img，延迟一般也在1~2秒或更快。

**Comment by starcwang** [comment]
@yangcanlin 计划中

**Comment by starcwang** [comment]
@yangcanlin google翻译在v3.3.0版本已支持
