### ISSUE TITLE
希望支持自定义注释格式，现在必须以javadoc的格式来，但是使用swagger的情况下不太方便

### ISSUE THREAD

**Issue by wholon** [starcwang/easy_javadoc#86]
如题

**Comment by wholon** [comment]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/55683600/231033231-256536cc-fb69-4749-be57-a34acbaf778a.png">

**Comment by kuolemax** [comment]
你这个属于代码生成了，不是这个插件的功能了
