### ISSUE TITLE
希望可以自动把成员变量的注释（JAVADOC）生成在GET/SET方法的注释中

### ISSUE THREAD

**Issue by ieclipse82** [starcwang/easy_javadoc#87]
例如可以生成以下形式的get/set方法，"上下文"前面的字“[获取]”可以自定义设置（示例中包括了中括号），多谢大佬
        /** 上下文 */
        Context context;

        /**
         * [获取]上下文
         */
        public Context getContext() {
            return context;
        }

        /**
         * [设置]上下文
         * @param context 
         */
        public void setContext(Context context) {
            this.context = context;
        }

**Comment by starcwang** [comment]
这个不在本插件javadoc范畴内，我还有个easy_generate插件，后续会增加生成带注释的getter、setter方法，实现此功能
