### ISSUE TITLE
错误反馈&建议添加自定义类注释

### ISSUE THREAD

**Issue by jonny6015** [starcwang/easy_javadoc#9]
标准类注释不支持@date
建议更换为@create

类注释不太全，也建议增加多个选项，如下：

/**
 * @version 1.0.0
 *
 * @Description 
 *
 * @author You
 *
 * @since 1.0.0
 *
 * @create ${YEAR}-${MONTH}-${DAY} ${HOUR}:${MINUTE}
 **/

**Comment by starcwang** [comment]
好建议，即将支持更多自定注解

**Comment by starcwang** [comment]
已经更新，1.6版本支持自定义模板功能
