### ISSUE TITLE
v3.3.1版本已添加git分支作为变量

### ISSUE THREAD

**Issue by NobiLee** [starcwang/easy_javadoc#91]
v3.3.1版本已添加git分支作为变量
![image](https://user-images.githubusercontent.com/18590960/236983117-6af2446c-4d01-4fce-9edf-79399ba21540.png)

_Originally posted by @starcwang in https://github.com/starcwang/easy_javadoc/issues/81#issuecomment-1539319651_
            
这个对于一个IDEA同时打开多个项目时，无法获取到当前项目
![image](https://github.com/starcwang/easy_javadoc/assets/52956291/7cf24279-78e7-4890-99e8-b0fcec9c235e)

由于分支存在beta feature release之类的前缀或业务相关的后缀，因此无法直接用做版本号，是否可以在当前project下面建一个指定的文件，比如.version 直接获取.version里面的文本作为版本号，或者新建一个easy_javadoc.properties之类的配置文件在当前project下，需要特定的配置属性可以开发人员根据自身需求添加？

**Comment by starcwang** [comment]
@NobiLee 添加文件的方式业务侵入性太大了，万一有的人提交到git仓库里，会让其它人感到困惑。
我把【这个对于一个IDEA同时打开多个项目时，无法获取到当前项目】问题修一下，【由于分支存在beta feature release之类的前缀或业务相关的后缀，因此无法直接用做版本号】这个问题可以用groovy脚本切割下字符串，比如： `branch.split("-")[1]`

**Comment by UFintech** [comment]
需要获取纯数字版本的Groovy脚本可使用下面这个
`def regex =  /(\d+(\.\d+){2,3})/;
def matcher = (branch =~ regex);
matcher.find() ? matcher.group(1) : "1.0.0";`
