### ISSUE TITLE
请问怎么增加时间注释？

### ISSUE THREAD

**Issue by Monster-DP** [starcwang/easy_javadoc#95]
请问怎么增加时间注释？

**Comment by kuolemax** [comment]
1. 使用自定义注释
```
/**
 * $DOC$
 *
 * $PARAMS$
 * $RETURN$
 * $THROWS$
 * @author $AUTHOR$
 * @date $DATE$
 */
```

2. 添加自定义变量

|方法名|类型|自定义值|
|---|---|---|
|$DATE$|Groovy脚本|$date|


<img width="1205" alt="image" src="https://github.com/starcwang/easy_javadoc/assets/25677528/6f7e7680-a76a-4fd4-b31c-42064e9b3d76">
